findtreasure:fileReader fileWriter treasureFinder main
	g++ fileReader.o fileWriter.o treasureFinder.o main.o -o findtreasure
fileReader:
	g++ -std=c++11 -c fileReader.cpp -o fileReader.o
fileWriter:
	g++ -std=c++11 -c fileWriter.cpp -o fileWriter.o
treasureFinder:
	g++ -std=c++11 -c treasureFinder.cpp -o treasureFinder.o
main:
	g++ -std=c++11 -c main.cpp -o main.o
	
	

